---

tailscale_authkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66613731383264333035343534396237373964343934393666383661303664396532396165306166
          6538333237353534356433653432356362633336333663380a653837366233373630363139343263
          39343230383430383130623938336566346437346630653235383565323237353665316236643038
          3130326631653138310a623562363231366364656336326533643633616535613265653333626134
          62663638393330393234636564346439663533336335383762316361306261306235653062663139
          63663963386539386132646563383039633962346166393030376662353132376365323761376362
          376431356639663937366138383635393037

# FIXME: generate a new key for idc
os_key_name: nate-treehouse

os_image: usegalaxy-node
os_flavor: m3.small
os_security_groups: [default, ssh-http-https]

host_groups:
  - name: idc
    gid: 808

host_users:
  - name: idc
    home: /home/idc
    uid: 808
    group: idc
    shell: /bin/sh

host_directories:
  - path: /jetstream2/scratch/idc
    owner: idc
    group: idc
    mode: "0755"

postgresql_objects_users:
  - name: idc
postgresql_objects_databases:
  - name: idc
    owner: idc

nginx_flavor: core
nginx_enable_default_server: false
nginx_servers:
  - idc-build

galaxy_layout: root-dir
galaxy_root: /srv/galaxy
galaxy_user:
  name: idc
galaxy_server_dir: /cvmfs/main.galaxyproject.org/galaxy
galaxy_venv_dir: /cvmfs/main.galaxyproject.org/venv
galaxy_config_dir: "{{ galaxy_root }}/config"
galaxy_shed_tools_dir: /jetstream2/scratch/idc/shed_tools
galaxy_manage_clone: false
galaxy_manage_download: false
galaxy_manage_existing: false
galaxy_manage_paths: true
galaxy_manage_static_setup: true
galaxy_manage_mutable_setup: true
galaxy_manage_database: false
galaxy_fetch_dependencies: false
galaxy_build_client: false
galaxy_backup_configfiles: false
galaxy_manage_gravity: true

galaxy_privsep_dirs:
  - "{{ galaxy_config_dir }}"
  - "{{ galaxy_config_dir }}/tpv"
galaxy_config_templates:
  - src: templates/idc/tpv/idc.yaml.j2
    dest: "{{ galaxy_config_dir }}/tpv/idc.yaml"
galaxy_config:
  gravity:
    process_manager: systemd
    galaxy_user: idc
    galaxy_group: idc
    galaxy_root: "{{ galaxy_server_dir }}"
    virtualenv: "{{ galaxy_venv_dir }}"
    gunicorn:
      bind: localhost:8080
      workers: 1
    handlers:
      handler:
        processes: 1
        pools:
          - job-handlers
          - workflow-schedulers
  galaxy:
    database_connection: postgresql:///idc
    conda_auto_init: false
    conda_auto_install: false
    allow_user_creation: false
    require_login: true
    admin_users:
      - idc@galaxyproject.org
    file_path: /jetstream2/scratch/idc/objects
    job_working_directory: /jetstream2/scratch/idc/jobs
    object_store_store_by: uuid
    container_resolvers:
      - type: cached_mulled_singularity
        cache_directory: /cvmfs/singularity.galaxyproject.org/all
        cache_directory_cacher_type: dir_mtime
      #- type: mulled_singularity
      #  cache_directory: /jetstream2/scratch/idc/singularity
      - type: explicit_singularity
    job_config:
      runners:
        local:
          load: galaxy.jobs.runners.local:LocalJobRunner
          workers: 1
        slurm:
          load: galaxy.jobs.runners.slurm:SlurmJobRunner
          workers: 2
          drmaa_library_path: /usr/lib64/libdrmaa.so.1
      handling:
        assign:
          - db-skip-locked
      execution:
        default: tpv_dispatcher
        environments:
          tpv_dispatcher:
            runner: dynamic
            type: python
            function: map_tool_to_destination
            rules_module: tpv.rules
            tpv_config_files:
              - "{{ galaxy_config_dir }}/tpv/idc.yaml"
