---

- import_tasks: secrets.yml

- include_tasks: spawn.yml
  when:
    - os_image is defined
    - os_flavor is defined
    - os_key_name is defined
    - os_nics is defined
    - os_security_groups is defined
