#!/usr/bin/env python3
"""Write ``schemas/request.schema.json``: the JSON Schema for request files.

The base is exported from the pydantic ``Request`` model, so it can never drift
from what the lint enforces. On top, every known data manager ``tool_id`` gets
its own ``params`` schema fetched from the Tool Shed (see ``tool_schemas.py``)
and attached with ``if tool_id == <guid> then params must match``. Editors that
honour the ``# yaml-language-server: $schema=`` modeline use this file for
completion and inline errors, and the lint uses its ``$defs`` to check
``params`` without the network.

Known tool_ids are the union of

- every request file under ``data-managers/`` (always), and
- ``schemas/data_managers.yml``: the data managers installed on the build
  Galaxy, resolved from usegalaxy-tools' ``data_managers.yml.lock`` with
  ``--from-lock`` so contributors get completion for a tool before anyone has
  requested data from it.

    python scripts/generate_schema.py            # (re)write, reusing committed $defs
    python scripts/generate_schema.py --refresh  # refetch every tool's schema
    python scripts/generate_schema.py --check --refresh   # CI: committed file == model + Tool Shed
    python scripts/generate_schema.py --from-lock https://raw.githubusercontent.com/galaxyproject/usegalaxy-tools/master/test.galaxyproject.org/data_managers.yml.lock

``--check`` without ``--refresh`` reuses the committed ``$defs``, so it only
proves the model part and the set of tool_ids; with ``--refresh`` the tool
schemas are compared against what the Tool Shed serves today.
"""
import argparse
import json
import sys
import urllib.request
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from request_models import Request, iter_request_files  # noqa: E402
from tool_schemas import (  # noqa: E402
    COMMITTED_SCHEMA,
    REPO_ROOT,
    SchemaResolver,
    SchemaSource,
    SchemaUnavailable,
    def_name,
    embed,
    repository_tool_ids,
    unresolvable_refs,
)

SCHEMA_ID = "https://raw.githubusercontent.com/galaxyproject/idc/main/schemas/request.schema.json"
INSTALLED_LIST = REPO_ROOT / "schemas" / "data_managers.yml"


def tool_ids_in_use() -> list[str]:
    guids = set()
    for path in iter_request_files():
        try:
            doc = yaml.safe_load(path.read_text())
        except yaml.YAMLError as exc:
            raise SystemExit(f"error: {path.relative_to(REPO_ROOT)}: invalid YAML: {exc}")
        if isinstance(doc, dict) and isinstance(doc.get("tool_id"), str):
            guids.add(doc["tool_id"])
    return sorted(guids)


def installed_tool_ids(path: Path = INSTALLED_LIST) -> list[str]:
    """GUIDs of the data managers listed in schemas/data_managers.yml (empty if absent)."""
    if not path.is_file():
        return []
    doc = yaml.safe_load(path.read_text()) or {}
    return sorted({guid for repo in doc.get("repositories", []) for guid in repo.get("tool_ids", [])})


def all_tool_ids() -> list[str]:
    return sorted(set(tool_ids_in_use()) | set(installed_tool_ids()))


def resolve_lock(source: str) -> dict:
    """usegalaxy-tools data_managers.yml.lock (URL or path) -> the schemas/data_managers.yml document."""
    if source.startswith(("http://", "https://")):
        req = urllib.request.Request(source, headers={"User-Agent": "idc-request-lint/1.0"})
        with urllib.request.urlopen(req, timeout=60) as resp:  # noqa: S310
            lock = yaml.safe_load(resp.read())
    else:
        lock = yaml.safe_load(Path(source).read_text())
    repositories = []
    failures = []
    for repo in sorted(lock.get("tools", []), key=lambda r: (r["owner"], r["name"])):
        try:
            revision, guids = repository_tool_ids(repo["owner"], repo["name"], repo.get("revisions", []))
        except SchemaUnavailable as exc:
            failures.append(str(exc))
            continue
        repositories.append({"owner": repo["owner"], "name": repo["name"], "revision": revision, "tool_ids": guids})
        print(f"  {repo['owner']}/{repo['name']} @ {revision}: {len(guids)} tool(s)", file=sys.stderr)
    for f in failures:
        print(f"::warning:: {f}", file=sys.stderr)
    return {"source": source, "repositories": repositories}


def write_installed_list(doc: dict, path: Path = INSTALLED_LIST) -> None:
    header = (
        "# Data managers installed on the build Galaxy, resolved to tool GUIDs at their\n"
        "# latest installed revision. Generated by\n"
        "#   python scripts/generate_schema.py --from-lock <data_managers.yml.lock>\n"
        "# Their parameter schemas are baked into request.schema.json so editors can\n"
        "# complete params for any of them. Do not edit by hand.\n"
    )
    path.write_text(header + yaml.safe_dump(doc, sort_keys=False, default_flow_style=False))


def build_schema(guids: list[str], resolve: SchemaResolver, required: set[str] | None = None) -> dict:
    base = Request.model_json_schema()
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": SCHEMA_ID,
        "title": "IDC reference-data request",
        "description": (
            "One requested reference-data version: data-managers/<data_manager>/<version>.yaml. "
            "Generated by scripts/generate_schema.py - do not edit by hand."
        ),
        "type": "object",
        "additionalProperties": False,
        "properties": base["properties"],
        "required": base["required"],
    }
    defs = {}
    conditions = []
    for guid in guids:
        try:
            params_schema = resolve(guid)
            dangling = unresolvable_refs(params_schema)
            if dangling:
                raise SchemaUnavailable(f"the served schema has unresolvable references {dangling}")
        except SchemaUnavailable as exc:
            # A tool nobody has requested data from yet may simply not be
            # schema-capable; one a request file names must be.
            if required is None or guid in required:
                raise
            print(f"::warning:: skipping {guid}: {exc}", file=sys.stderr)
            continue
        name = def_name(guid)
        defs[name] = embed(params_schema, name)
        conditions.append(
            {
                "if": {"properties": {"tool_id": {"const": guid}}, "required": ["tool_id"]},
                "then": {"properties": {"params": {"$ref": f"#/$defs/{name}"}}},
            }
        )
    if defs:
        schema["$defs"] = defs
        schema["allOf"] = conditions
    return schema


def render(schema: dict) -> str:
    return json.dumps(schema, indent=2, sort_keys=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="Exit 1 if the committed schema differs from a fresh one")
    parser.add_argument("--refresh", action="store_true", help="Refetch every tool's schema instead of reusing committed $defs")
    parser.add_argument("--output", type=Path, default=COMMITTED_SCHEMA)
    parser.add_argument(
        "--from-lock",
        metavar="URL_OR_PATH",
        help="Rewrite schemas/data_managers.yml from this usegalaxy-tools data_managers.yml.lock, then generate",
    )
    args = parser.parse_args(argv)

    if args.from_lock:
        if args.check:
            parser.error("--from-lock rewrites schemas/data_managers.yml; it cannot be combined with --check")
        write_installed_list(resolve_lock(args.from_lock))
        print(f"wrote {INSTALLED_LIST.relative_to(REPO_ROOT)}")

    resolve = SchemaSource(committed=None if args.refresh else args.output)
    try:
        schema = build_schema(all_tool_ids(), resolve, required=set(tool_ids_in_use()))
    except SchemaUnavailable as exc:
        print(f"error: could not fetch a tool's parameter schema: {exc}", file=sys.stderr)
        return 1
    text = render(schema)
    rel = args.output.relative_to(REPO_ROOT) if args.output.is_relative_to(REPO_ROOT) else args.output

    if args.check:
        current = args.output.read_text() if args.output.is_file() else None
        if current != text:
            print(
                f"error: {rel} is stale - run `python scripts/generate_schema.py` and commit the result",
                file=sys.stderr,
            )
            return 1
        print(f"ok: {rel} is up to date ({len(schema.get('$defs', {}))} tool schema(s))")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f"wrote {rel} ({len(schema.get('$defs', {}))} tool schema(s))")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
