- name: Spawn instance
  hosts: idc_builders
  gather_facts: no
  environment:
    OS_CLOUD: "{{ os_cloud_id }}"
    OS_IDENTITY_API_VERSION: '3'
  roles:
    - openstack

- name: Configure Galaxy
  hosts: idc_builders
  tasks:
    - name: Install slurm-drmaa
      dnf:
        name: https://github.com/natefoo/slurm-drmaa/releases/download/1.1.3/slurm-drmaa-1.1.3-20.11.el8.x86_64.rpm
        disable_gpg_check: true
    - import_role:
        name: galaxyproject.general.virtual
    - import_role:
        name: galaxyproject.general.packages
    - import_role:
        name: galaxyproject.general.users
    - import_role:
        name: galaxyproject.general.paths
    - import_role:
        name: galaxyproject.galaxy
    - name: Flush handlers
      meta: flush_handlers
    - name: Copy bootstrap script
      copy:
        src: files/idc/bootstrap.sh
        dest: /srv/galaxy/bootstrap.sh
        owner: root
        group: idc
        mode: "0750"
    - name: Create admin user
      command: /srv/galaxy/bootstrap.sh
      become: true
      become_user: idc
      register: _bootstrap_result
    - name: Bootstrap result
      debug:
        var: _bootstrap_result
    - import_role:
        name: galaxyproject.nginx
    - import_role:
        name: artis3n.tailscale
