- name: Clean up instance
  hosts: idc_builders
  tasks:
    - name: Remove scratch directory
      file:
        path: /jetstream2/scratch/idc
        state: absent
      diff: false
    - name: Create logs directory
      file:
        path: /jetstream2/scratch/idc-build-logs
        owner: rocky
        group: rocky
        mode: "0755"
        state: directory
    - name: Dump gunicorn logs
      shell: journalctl -u galaxy-gunicorn.service > /jetstream2/scratch/idc-build-logs/gunicorn-{{ lookup('ansible.builtin.env', 'BUILD_NUMBER') | default('unknown') }}.log
      become_user: rocky
    - name: Log out from tailnet
      command: tailscale logout

- name: Destroy instance
  hosts: idc_builders
  gather_facts: no
  environment:
    OS_CLOUD: "{{ os_cloud_id }}"
    OS_IDENTITY_API_VERSION: '3'
  tasks:
    - import_tasks: roles/openstack/tasks/secrets.yml
    - name: Destroy instance
      os_server:
        name: "{{ os_name | default(inventory_hostname) }}"
        state: absent
      delegate_to: localhost
    - import_tasks: roles/openstack/tasks/clean.yml
