- name: Clean up instane
  hosts: idc_builders
  tasks:
    - name: Remove scratch directory
      file:
        path: /jetstream2/scratch/idc
        state: absent
      diff: false
    - name: Log out from tailnet
      command: tailscale logout

- name: Destroy instance
  hosts: idc_builders
  gather_facts: no
  environment:
    OS_CLOUD: "{{ os_cloud_id }}"
    OS_IDENTITY_API_VERSION: '3'
  tasks:
    - import_tasks: roles/openstack/tasks/secrets.yml
    - name: Destroy instance
      os_server:
        name: "{{ os_name | default(inventory_hostname) }}"
        state: absent
      delegate_to: localhost
    - import_tasks: roles/openstack/tasks/clean.yml
